name: Testing github actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  greetings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello
        run: echo "Hello!"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Bye
        run: echo "Bye!"
        shell: bash
